services:
  api:
    build: ./backend
    container_name: smart_workflow_automation_api
    command: uvicorn app.main:app --host 0.0.0.0 --port ${API_PORT} --reload
    ports:
      - "${API_PORT}:${API_PORT}"
    env_file:
      - ./.env
    depends_on:
      - rabbitmq
      - postgres
      - ollama-server
    networks:
      - workflow-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock


  mlflow:
    build: ./backend
    container_name: smart_workflow_automation_mlflow
    command: mlflow ui --host 0.0.0.0 --port 5001 --backend-store-uri ./mlruns
    networks:
      - workflow-network
    ports:
      - "5001:5001"
    volumes:
      - .:/app
    depends_on:
      - api


  ollama-server:
    image: ollama/ollama
    command: /bin/ollama serve
    networks:
      - workflow-network
    ports:
      - "11434:11434"


  worker:
    build: ./backend
    container_name: smart_workflow_automation_worker
    command: celery -A app.workers.tasks.celery_app worker --loglevel=info
    env_file:
      - ./.env
    depends_on:
      - rabbitmq
      - postgres
    networks:
      - workflow-network


  rabbitmq:
    image: rabbitmq:4-management
    container_name: smart_workflow_automation_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    env_file:
      - ./.env
    networks:
      - workflow-network
    ports:
      - "5672:5672"      # AMQP port
      - "15672:15672"    # RabbitMQ management UI


  postgres:
    image: postgres:15
    container_name: smart_workflow_automation_postgres
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - workflow-network
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  redis:
    image: redis:7
    container_name: smart_workflow_automation_redis
    networks:
      - workflow-network
    ports:
      - "6379:6379"


  airflow-webserver:
    # build:
    #   context: ./backend
    #   dockerfile: airflow/Dockerfile
    image: apache/airflow:2.8.1
    container_name: smart_workflow_automation_airflow
    environment:
      - PYTHONPATH=/opt/airflow
      - AIRFLOW__API__AUTH_BACKEND=${AIRFLOW__API__AUTH_BACKEND}
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=${AIRFLOW__CORE__SQL_ALCHEMY_CONN}
    depends_on:
      - postgres
    command: >
      bash -c "airflow db init &&
              airflow users create --username ${AIRFLOW_USERNAME} --password ${AIRFLOW_PASSWORD} --firstname ${AIRFLOW_FIRST_NAME} --lastname ${AIRFLOW_LAST_NAME} --role ${AIRFLOW_ROLE} --email ${AIRFLOW_EMAIL} &&
              airflow webserver"
    volumes:
      - ./backend/airflow/dags:/opt/airflow/dags
      - ./backend/airflow/logs:/opt/airflow/logs
      - ./backend/airflow/plugins:/opt/airflow/plugins
      - ./backend/app:/opt/airflow/app
    ports:
      - "8080:8080"
    restart: always
    networks:
      - workflow-network


  airflow-scheduler:
    # build:
    #   context: ./backend
    #   dockerfile: airflow/Dockerfile
    image: apache/airflow:2.8.1
    container_name: airflow_scheduler
    environment:
      - PYTHONPATH=/opt/airflow
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=${AIRFLOW__CORE__SQL_ALCHEMY_CONN}
    depends_on:
      - airflow-webserver
    command: airflow scheduler
    volumes:
      - ./backend/airflow/dags:/opt/airflow/dags
      - ./backend/airflow/logs:/opt/airflow/logs
      - ./backend/airflow/plugins:/opt/airflow/plugins
      - ./backend/app:/opt/airflow/app
    networks:
      - workflow-network

volumes:
  postgres_data:

networks:
  workflow-network:
    driver: bridge